name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "corona-dashboard-mbcn"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          dockerfile_path: ''
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web